export const GET_BEER_STARTED = 'GET_BEER_STARTED';

export const GET_BEER_LIST_SUCCESS = 'GET_BEER_LIST_STARTED';
export const GET_BEER_LIST_FAILURE = 'GET_BEER_LIST_STARTED';

export const GET_BEER_SUCCESS = 'GET_BEER_INFO_SUCCESS';
export const GET_BEER_FAILURE = 'GET_BEER_INFO_FAILURE';

export const ADD_FAVORITE_BEER = 'ADD_FAVORITE_BEER';
export const REMOVE_FAVORITE_BEER = 'REMOVE_FAVORITE_BEERS';
export const GET_FAVORITE_BEERS_SUCCESS = 'GET_FAVORITE_BEERS_SUCCESS';
