export const GET_BEER_STARTED = 'GET_BEER_STARTED';

export const GET_BEER_LIST_SUCCESS = 'GET_BEER_LIST_STARTED';
export const GET_BEER_LIST_FAILURE = 'GET_BEER_LIST_STARTED';

export const GET_BEER_SUCCESS = 'GET_BEER_INFO_SUCCESS';
export const GET_BEER_FAILURE = 'GET_BEER_INFO_FAILURE';

export const SET_FAVORITE_BEERS = 'SET_FAVORITE_BEERS';
export const ADD_FAVORITE_BEER = 'ADD_FAVORITE_BEER';
export const REMOVE_FAVORITE_BEER = 'REMOVE_FAVORITE_BEERS';
export const GET_FAVORITE_BEERS_SUCCESS = 'GET_FAVORITE_BEERS_SUCCESS';

export const SEARCH_BEERS_SUCCESS = 'SEARCH_BEERS_SUCCESS';
export const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS';
export const RESET_SEARCH_PARAMS = 'RESET_SEARCH_PARAMS';

export const GET_BEER_INFO_SUCCESS = 'GET_BEER_INFO_SUCCESS';
